"""add tenant_id to users table

Revision ID: 36cf2923c6a5
Revises: 283f932dc94d
Create Date: 2026-07-13 09:59:33.210992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36cf2923c6a5'
down_revision: Union[str, Sequence[str], None] = '283f932dc94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='tenantstatus'),
               nullable=False)
    op.create_unique_constraint(None, 'tenants', ['owner_user_id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'account_type',
               existing_type=mysql.ENUM('individual', 'organization', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('INDIVIDUAL', 'ORGANIZATION', name='accounttype'),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'account_type',
               existing_type=sa.Enum('INDIVIDUAL', 'ORGANIZATION', name='accounttype'),
               type_=mysql.ENUM('individual', 'organization', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='tenantstatus'),
               type_=mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###
