"""add is_deleted column to users table for soft delete

Revision ID: 9d67617af305
Revises: da52894cc578
Create Date: 2026-07-13 11:29:52.209618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d67617af305'
down_revision: Union[str, Sequence[str], None] = 'da52894cc578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###      
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ## end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    
    # ### end Alembic commands ###
