"""fix user model: lowercase enums, add role column

Revision ID: da52894cc578
Revises: 36cf2923c6a5
Create Date: 2026-07-13 10:16:58.870420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da52894cc578'
down_revision: Union[str, Sequence[str], None] = '36cf2923c6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('active', 'inactive', name='tenantstatus'),
               nullable=True)
    
    op.add_column('users', sa.Column('role', sa.Enum('tenant_admin', 'member', name='userrole'), nullable=True))
    op.alter_column('users', 'account_type',
               existing_type=mysql.ENUM('INDIVIDUAL', 'ORGANIZATION', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('individual', 'organization', name='accounttype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=sa.Enum('individual', 'organization', name='accounttype'),
               type_=mysql.ENUM('INDIVIDUAL', 'ORGANIZATION', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    
    
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('active', 'inactive', name='tenantstatus'),
               type_=mysql.ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE', collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###
